export interface SubscriptionPackage {
  id: number;
  name: string;
  allowedAccountType: 'SingleUser' | 'Company';
  monthlyPrice: number;
  annualPrice: number;
  dataRetentionDays: number;
  minVehicles: number;
  maxVehicles: number;
  maxFleetManagers: number;
  maxDrivers: number;
  isOwnTrackerDevice: boolean;
  hasFuelAndMaintenance: boolean;
  hasPortalAccess: boolean;
  isActive: boolean;
}

export const subscriptionPackages: SubscriptionPackage[] = [
  {
    id: 1,
    name: 'Single User - Basic',
    allowedAccountType: 'SingleUser',
    monthlyPrice: 599,
    annualPrice: 5999,
    dataRetentionDays: 7,
    minVehicles: 1,
    maxVehicles: 1,
    maxFleetManagers: 1,
    maxDrivers: 0,
    isOwnTrackerDevice: false,
    hasFuelAndMaintenance: false,
    hasPortalAccess: false,
    isActive: true,
  },
  {
    id: 2,
    name: 'Single User - Standard',
    allowedAccountType: 'SingleUser',
    monthlyPrice: 999,
    annualPrice: 0,
    dataRetentionDays: 7,
    minVehicles: 1,
    maxVehicles: 1,
    maxFleetManagers: 1,
    maxDrivers: 0,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: false,
    hasPortalAccess: false,
    isActive: true,
  },
  {
    id: 3,
    name: 'Single User - Advanced',
    allowedAccountType: 'SingleUser',
    monthlyPrice: 1499,
    annualPrice: 14999,
    dataRetentionDays: 30,
    minVehicles: 1,
    maxVehicles: 1,
    maxFleetManagers: 1,
    maxDrivers: 0,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: false,
    isActive: true,
  },
  {
    id: 4,
    name: 'Single User - Pro',
    allowedAccountType: 'SingleUser',
    monthlyPrice: 1999,
    annualPrice: 19999,
    dataRetentionDays: 30,
    minVehicles: 1,
    maxVehicles: 3,
    maxFleetManagers: 1,
    maxDrivers: 0,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: true,
    isActive: true,
  },
  {
    id: 5,
    name: 'Corporate - Basic (45 Days)',
    allowedAccountType: 'Company',
    monthlyPrice: 18000,
    annualPrice: 180000,
    dataRetentionDays: 45,
    minVehicles: 1,
    maxVehicles: 10,
    maxFleetManagers: 2,
    maxDrivers: 10,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: true,
    isActive: true,
  },
  {
    id: 6,
    name: 'Corporate - Basic (60 Days)',
    allowedAccountType: 'Company',
    monthlyPrice: 19000,
    annualPrice: 190000,
    dataRetentionDays: 60,
    minVehicles: 1,
    maxVehicles: 10,
    maxFleetManagers: 2,
    maxDrivers: 10,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: true,
    isActive: true,
  },
  {
    id: 7,
    name: 'Corporate - Basic (90 Days)',
    allowedAccountType: 'Company',
    monthlyPrice: 20000,
    annualPrice: 200000,
    dataRetentionDays: 90,
    minVehicles: 1,
    maxVehicles: 10,
    maxFleetManagers: 2,
    maxDrivers: 10,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: true,
    isActive: true,
  },
  {
    id: 8,
    name: 'Corporate - Standard (45 Days)',
    allowedAccountType: 'Company',
    monthlyPrice: 30000,
    annualPrice: 300000,
    dataRetentionDays: 45,
    minVehicles: 1,
    maxVehicles: 25,
    maxFleetManagers: 5,
    maxDrivers: 25,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: true,
    isActive: true,
  },
  {
    id: 9,
    name: 'Corporate - Standard (60 Days)',
    allowedAccountType: 'Company',
    monthlyPrice: 32500,
    annualPrice: 325000,
    dataRetentionDays: 60,
    minVehicles: 1,
    maxVehicles: 25,
    maxFleetManagers: 5,
    maxDrivers: 25,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: true,
    isActive: true,
  },
  {
    id: 10,
    name: 'Corporate - Standard (90 Days)',
    allowedAccountType: 'Company',
    monthlyPrice: 35000,
    annualPrice: 350000,
    dataRetentionDays: 90,
    minVehicles: 1,
    maxVehicles: 25,
    maxFleetManagers: 5,
    maxDrivers: 25,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: true,
    isActive: true,
  },
  {
    id: 11,
    name: 'Corporate - Pro (45 Days)',
    allowedAccountType: 'Company',
    monthlyPrice: 90000,
    annualPrice: 975000,
    dataRetentionDays: 45,
    minVehicles: 1,
    maxVehicles: 75,
    maxFleetManagers: 10,
    maxDrivers: 75,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: true,
    isActive: true,
  },
  {
    id: 12,
    name: 'Corporate - Pro (60 Days)',
    allowedAccountType: 'Company',
    monthlyPrice: 97500,
    annualPrice: 975000,
    dataRetentionDays: 60,
    minVehicles: 1,
    maxVehicles: 100,
    maxFleetManagers: 10,
    maxDrivers: 75,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: true,
    isActive: true,
  },
  {
    id: 13,
    name: 'Corporate - Pro (90 Days)',
    allowedAccountType: 'Company',
    monthlyPrice: 105000,
    annualPrice: 1050000,
    dataRetentionDays: 90,
    minVehicles: 1,
    maxVehicles: 75,
    maxFleetManagers: 10,
    maxDrivers: 75,
    isOwnTrackerDevice: true,
    hasFuelAndMaintenance: true,
    hasPortalAccess: true,
    isActive: true,
  },
];
